# Routing configuration for the FOSJsRoutingBundle which allows for dynamic
# javascript routing.
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

##
# JSON routes: These are part of the json api and will be split into a separate file eventually.
##
json_decks:
    path:  /json/deck
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:all, _format: json }
    methods: [GET]

json_deck_create:
    path:  /json/deck
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:create, _format: json }
    methods: [POST]

json_deck_view:
    path:  /json/deck/{deckId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:get, _format: json }
    requirements:
        deckId: \d+
    methods: [GET]

json_deck_update:
    path:  /json/deck/{deckId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:update, _format: json }
    requirements:
        deckId: \d+
    methods: [POST]

json_deck_delete:
    path:  /json/deck/{deckId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:remove, _format: json }
    requirements:
        deckId: \d+
    methods: [DELETE]

json_deck_image:
    path:  /json/deck/{deckId}/image
    defaults: {_controller: TylerTopTrumpsBundle:JSONDeck:getDeckImage }
    requirements:
        deckId: \d+
    methods: [GET]

json_card_view:
    path:  /json/deck/{deckId}/card/{cardId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONCard:get, _format: json }
    requirements:
        deckId: \d+
        cardId: \d+
    methods: [GET]

json_card_delete:
    path:  /json/deck/{deckId}/card/{cardId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONCard:remove, _format: json }
    requirements:
        deckId: \d+
        cardId: \d+
    methods: [DELETE]

json_card_update:
    path:  /json/deck/{deckId}/card/{cardId}
    defaults: {_controller: TylerTopTrumpsBundle:JSONCard:update, _format: json }
    requirements:
        deckId: \d+
        cardId: \d+
    methods: [POST]

json_card_create:
    path:  /json/deck/{deckId}/card
    defaults: {_controller: TylerTopTrumpsBundle:JSONCard:create, _format: json }
    requirements:
        deckId: \d+
    methods: [POST]

json_card_image:
    path:  /json/deck/{deckId}/card/{cardId}/image
    defaults: {_controller: TylerTopTrumpsBundle:JSONCard:getCardImage }
    requirements:
        deckId: \d+
        cardId: \d+
    methods: [GET]

##
# Template routes for the top trumps application.
##
template_card_create_display:
    path: /admin/deck/{deckId}/card
    defaults: {_controller: TylerTopTrumpsBundle:Deck:newCardDisplay }
    requirements:
        deckId: \d+
    methods: [GET]

template_card_edit_display:
    path: /admin/deck/{deckId}/card/{cardId}
    defaults: {_controller: TylerTopTrumpsBundle:Deck:editCardDisplay }
    requirements:
        deckId: \d+
        cardId: \d+
    methods: [GET]

template_all_deck_view:
    path: /admin
    defaults: {_controller: TylerTopTrumpsBundle:Deck:viewDecksDisplay }
    methods: [GET]